### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by sam-sk** [pe7er/db8sitelastmodified#1]
Hi Pe7er

On a multilanguage site, the month is displayed in English (e.g; 30 March 2015). Is it a problem of my language pack (I searched through my Language manager override and don't find English months in my Joomla language pack) or it is how this extension works? Is there a way I can add an override the months to be in my native language? 
Thanks

**Comment by pe7er** [comment]
Hi Sam,

In https://github.com/pe7er/db8sitelastmodified/blob/master/helper.php the date format is retrieved from the parameters with $date->format($params->get('dateformat', 'l d-m-Y, H:i:s')

It uses the PHP date format, see: http://php.net/manual/en/function.date.php. 
"l d F Y, H:i:s" would be something like 31 March 2015, 23:30:59

I don't think that you can override it. You could try to edit the helper.php and use setlocale & strftime: http://php.net/manual/en/function.setlocale.php

Sorry I do not have time at the moment to change this module with such functionality.
Kind regards,
Peter

**Comment by sam-sk** [comment]
Thanks. That works!
